Repository openshift/cluster-dns-operator, pull requests merged in 2018-11, with the labels that each got.

#44 manifests: allow dns operator to schedule on any node
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
Labels: approved, lgtm, size/XS

#45 Do no generate bindata for manifests used by CVO
  hack/update-generated-bindata.sh
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#47 release-local.sh fixes
  hack/release-local.sh
Labels: approved, lgtm, size/S

#48 Fix dns service reconciliation
  pkg/stub/handler.go
Labels: approved, lgtm, size/S

#50 Add baseline end-to-end tests
  Makefile
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#52 Make CoreDNS image configurable
  assets/dns/daemonset.yaml
  cmd/cluster-dns-operator/main.go
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  manifests/image-references
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/config.go
  test/manifests/manifests.go
Labels: approved, lgtm, size/M

#53 Improve unit test
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/S

#54 Improve the docs
  HACKING.md
  README.md
  hack/uninstall.sh
Labels: approved, lgtm, size/M
