Repository openshift/cluster-dns-operator, pull requests merged in 2018-09, with the labels that each got.

#7 Cluster DNS operator changes to create basic resources
  HACKING.md
  Makefile
  README.md
  assets/dns/cluster-role-binding.yaml
  assets/dns/cluster-role.yaml
  assets/dns/configmap.yaml
  assets/dns/daemonset.yaml
  assets/dns/namespace.yaml
  assets/dns/service-account.yaml
  assets/dns/service.yaml
  deploy/cr.yaml
  deploy/rbac.yaml
  examples/config/config.yaml
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/XXL

#8 Configure DNS deployment from ClusterDNS
  assets/dns/service.yaml
  config/config.yaml
  deploy/cr.yaml
  examples/config/config.yaml
  pkg/apis/dns/v1alpha1/types.go
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L

#9 Makefile should generate bindata before the build
  Makefile
Labels: approved, lgtm, size/XS

#10 Restore config/config.yaml, needed by operator-sdk
  config/config.yaml
Labels: approved, lgtm, size/XS

#11 Added basic integration tests for cluster dns operator
  HACKING.md
  Makefile
  pkg/manifests/manifests.go
  test/assets/app-dns/deployment.yaml
  test/assets/app-dns/namespace.yaml
  test/assets/app-dns/service.yaml
  test/assets/cluster-dns-cr.yaml
  test/integration/integration_test.go
  test/manifests/bindata.go
  test/manifests/manifests.go
Labels: approved, lgtm, size/XL

#12 Remove unused junk
  .gitignore
  tmp/build/Dockerfile
  tmp/build/build.sh
  tmp/build/docker_build.sh
  tmp/codegen/boilerplate.go.txt
  tmp/codegen/update-generated.sh
Labels: approved, lgtm, size/M

#13 update to flat updatepayload structure
  images/cluster-dns-operator/Dockerfile
  manifests/00_clusterdnsoperator_00_clusterdns.crd.yaml
  manifests/00_clusterdnsoperator_01_clusterdns.yaml
  manifests/00_clusterdnsoperator_02_roles.yaml
  test/integration/integration_test.go
Labels: approved, lgtm, size/XS

#14 Added cluster DNS operator manifest
  Makefile
  manifests/00_clusterdnsoperator_00_namespace.yaml
  manifests/00_clusterdnsoperator_02_roles.yaml
  manifests/00_clusterdnsoperator_03_operator.yaml
Labels: approved, lgtm, size/M

#15 Do not use 'operator' name for dns cluster role and role bindings
  assets/dns/cluster-role-binding.yaml
  assets/dns/cluster-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#16 Fixed rbac roles for cluster DNS operator
  manifests/00_clusterdnsoperator_02_roles.yaml
Labels: approved, lgtm, size/S

#20 Add image references
  manifests/image-references
Labels: approved, lgtm, size/XS

#23 Make dns daemonset, configmap and service creation specific to given custom resource
  Makefile
  assets/dns/configmap.yaml
  assets/dns/daemonset.yaml
  assets/dns/service.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/M
