Repository openshift/cluster-dns-operator, pull requests merged in 2018-10, with the labels that each got.

#27 Allow role to get objects for getting installer config map.
  manifests/00-cluster-role.yaml
Labels: approved, lgtm, size/XS

#30 Revert "Merge pull request #28 from pravisankar/fix-rbac-roles"
  assets/dns/namespace.yaml
  manifests/00-cluster-role.yaml
  manifests/00-namespace.yaml
  manifests/00-role.yaml
  manifests/01-cluster-role-binding.yaml
  manifests/01-role-binding.yaml
  manifests/02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L

#31 Rename manifests to conform to runlevels
  manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
  manifests/0000_08_cluster-dns-operator_00-custom-resource-definition.yaml
  manifests/0000_08_cluster-dns-operator_00-namespace.yaml
  manifests/0000_08_cluster-dns-operator_01-cluster-role-binding.yaml
  manifests/0000_08_cluster-dns-operator_01-service-account.yaml
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/integration/integration_test.go
Labels: approved, lgtm, size/L

#25 Use cluster dns ip address from install config if "available"
  Gopkg.lock
  config/config.yaml
  pkg/stub/handler.go
  pkg/util/config.go
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
Labels: approved, lgtm, size/L

#32 Makefile changes to add targets for building local image and gofmt verification
  Makefile
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#34 update resources to avoid openshift cycles
  assets/dns/daemonset.yaml
  assets/dns/namespace.yaml
  manifests/0000_08_cluster-dns-operator_00-namespace.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#29 Changed delete handling to use garbage collection
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#35 Use multistage Dockerfile
  images/cluster-dns-operator/Dockerfile
Labels: approved, lgtm, size/M

#39 Make operator level-driven and fix cluster config usage
  cmd/cluster-dns-operator/main.go
  hack/uninstall.sh
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
  pkg/util/config.go
  pkg/util/config_test.go
  pkg/util/slice/slice.go
Labels: approved, lgtm, size/L

#42 Move Dockerfile for product builds
  Dockerfile
  Makefile
  hack/release-local.sh
Labels: approved, lgtm, size/XS
