Repository openshift/cluster-dns-operator, pull requests merged in 2018-12, with the labels that each got.

#60 Fix registry service name
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#59 Makefile: don't specify GOARCH
  Makefile
Labels: approved, lgtm, size/XS

#61 Support both relative and absolute service names
  assets/dns/daemonset.yaml
  hack/uninstall.sh
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#62 Assign system-cluster-critical priority to operator and component
  assets/dns/daemonset.yaml
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#41 Rename operator and dns namespaces
  assets/cluster-dns-cr.yaml
  assets/dns/cluster-role-binding.yaml
  assets/dns/cluster-role.yaml
  assets/dns/configmap.yaml
  assets/dns/daemonset.yaml
  assets/dns/namespace.yaml
  assets/dns/service-account.yaml
  assets/dns/service.yaml
  cmd/cluster-dns-operator/main.go
  hack/uninstall.sh
  manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
  manifests/0000_08_cluster-dns-operator_00-namespace.yaml
  manifests/0000_08_cluster-dns-operator_01-cluster-role-binding.yaml
  manifests/0000_08_cluster-dns-operator_01-role-binding.yaml
  manifests/0000_08_cluster-dns-operator_01-role.yaml
  manifests/0000_08_cluster-dns-operator_01-service-account.yaml
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#66 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#64 Make DNS CRD cluster scoped
  assets/cluster-dns-cr.yaml
  cmd/cluster-dns-operator/main.go
  config/config.yaml
  hack/uninstall.sh
  manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
  manifests/0000_08_cluster-dns-operator_00-custom-resource-definition.yaml
  manifests/0000_08_cluster-dns-operator_01-role.yaml
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/stub/handler.go
  pkg/stub/status.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M
