Repository openshift/cluster-dns-operator, pull requests merged in 2019-02, with the labels that each got.

#71 Update ClusterOperator API and fix name
  Gopkg.lock
  Gopkg.toml
  cmd/cluster-dns-operator/main.go
  pkg/stub/handler.go
  pkg/stub/status.go
  pkg/util/clusteroperator/status.go
  pkg/util/clusteroperator/status_test.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XXL

#73 Set requests on operator and on daemonset
  assets/dns/daemonset.yaml
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#74 manifests: Add ClusterOperator resource
  manifests/0000_08_cluster-dns-operator_03-cluster-operator.yaml
Labels: approved, lgtm, size/XS

#75 config: Replace install config with cluster config
  Gopkg.lock
  Gopkg.toml
  cmd/cluster-dns-operator/main.go
  manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
  pkg/util/config.go
  pkg/util/config_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/type_features.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#77 Move clusterIP and clusterDomain spec fields to status
  assets/cluster-dns-cr.yaml
  manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
  manifests/0000_08_cluster-dns-operator_00-custom-resource-definition.yaml
  pkg/apis/dns/v1alpha1/types.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L
