Repository openshift/cluster-dns-operator, pull requests merged in 2019-04, with the labels that each got.

#89 Removes static GOOS reference from Makefile
  Makefile
Labels: approved, lgtm, size/XS

#90 Rename 'Cluster DNS' references to 'DNS'
  Dockerfile
  Dockerfile.rhel7
  HACKING.md
  Makefile
  README.md
  cmd/dns-operator/main.go
  hack/release-local.sh
  manifests/0000_08_dns-operator_00-cluster-role.yaml
  manifests/0000_08_dns-operator_00-custom-resource-definition.yaml
  manifests/0000_08_dns-operator_00-namespace.yaml
  manifests/0000_08_dns-operator_01-cluster-role-binding.yaml
  manifests/0000_08_dns-operator_01-role-binding.yaml
  manifests/0000_08_dns-operator_01-role.yaml
  manifests/0000_08_dns-operator_01-service-account.yaml
  manifests/0000_08_dns-operator_02-deployment.yaml
  manifests/0000_08_dns-operator_03-cluster-operator.yaml
  pkg/manifests/manifests.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/names.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#95 Bug 1699488: Fixes DNS ClusterOperator Initial Status
  pkg/operator/controller/status.go
Labels: approved, do-not-merge/hold, lgtm, size/S

#91 Delete registration of client-go GCP auth plug-in
  cmd/dns-operator/main.go
Labels: approved, lgtm, size/XS

#98 Bug 1688969: Integrate coredns metrics with openshift-monitoring
  Gopkg.lock
  Gopkg.toml
  assets/dns/metrics/cluster-role-binding.yaml
  assets/dns/metrics/cluster-role.yaml
  assets/dns/metrics/role-binding.yaml
  assets/dns/metrics/role.yaml
  assets/dns/namespace.yaml
  assets/dns/service.yaml
  hack/uninstall.sh
  manifests/0000_08_dns-operator_00-cluster-role.yaml
  manifests/0000_08_dns-operator_01-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_service_monitor.go
  pkg/operator/controller/names.go
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/golang.org/x/sys/windows/mkerrors.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zerrors_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/imports/fix.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, lgtm, size/XXL

#99 Moves Operator Failing status to Degraded
  Gopkg.lock
  Gopkg.toml
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XL

#100 Add node-selector annotation to namespace
  assets/dns/namespace.yaml
  manifests/0000_08_dns-operator_00-namespace.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#101 Move component to an appropriate upgrade order (network)
  manifests/0000_70_dns-operator_00-cluster-role.yaml
  manifests/0000_70_dns-operator_00-custom-resource-definition.yaml
  manifests/0000_70_dns-operator_00-namespace.yaml
  manifests/0000_70_dns-operator_01-cluster-role-binding.yaml
  manifests/0000_70_dns-operator_01-role-binding.yaml
  manifests/0000_70_dns-operator_01-role.yaml
  manifests/0000_70_dns-operator_01-service-account.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  manifests/0000_70_dns-operator_03-cluster-operator.yaml
Labels: approved, lgtm, size/XS

#88 Bug 1690342: Initial DNS status conditions implementation
  pkg/operator/controller/controller.go
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/XL
