Repository openshift/cluster-dns-operator, pull requests merged in 2019-03, with the labels that each got.

#78 status: report cluster operator version from payload
  manifests/0000_08_cluster-dns-operator_02-deployment.yaml
  manifests/0000_08_cluster-dns-operator_03-cluster-operator.yaml
  pkg/stub/status.go
Labels: approved, lgtm, size/M

#79 Check RELEASE_VERSION env existence before starting the reconciliation.
  cmd/cluster-dns-operator/main.go
  hack/uninstall.sh
  manifests/0000_08_cluster-dns-operator_03-cluster-operator.yaml
  pkg/operator/config.go
  pkg/stub/status.go
  version/version.go
Labels: approved, lgtm, size/S

#81 Allow dns operator to update coreDNS image
  manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
  pkg/stub/handler.go
  pkg/stub/status.go
  pkg/stub/status_test.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/L

#83 Restore old coreDNS image and release version in operator e2e tests
  pkg/stub/status.go
  test/e2e/operator_test.go
Labels: approved, lgtm, size/M

#85 Bug 1687976: Allow update of node resolver image
  pkg/stub/handler.go
Labels: approved, lgtm, size/S

#84 Bug 1678472: Create external name service default/openshift to resolve 'openshift.default.svc' to 'kubernetes.default.svc'
  pkg/stub/handler.go
Labels: approved, lgtm, size/M
