Repository openshift/cluster-dns-operator, pull requests merged in 2019-12, with the labels that each got.

#144 Bug 1778529: daemonsetConfigChanged: Check tolerations
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#148 Bug 1779490: Handle missing pids during sidecar teardown
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#150 [release-4.2] Bug 1780213: Don't start DNS on NotReady nodes
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#151 Node resolver: support IPv6 service IPs
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S
