Repository openshift/cluster-dns-operator, pull requests merged in 2019-06, with the labels that each got.

#114 Fix operator's terminationGracePeriodSeconds
  assets/dns/daemonset.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#118 Bug 1717734: status: add related dnses to operator status
  pkg/operator/controller/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#117 metrics: fix metrics registration bug
  pkg/operator/controller/controller.go
Labels: approved, lgtm, size/XS

#120 Dockerfile.rhel7: Use golang-1.12
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#121 daemonsetConfigChanged: Check node selector
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
Labels: approved, lgtm, size/M
