Repository openshift/cluster-dns-operator, pull requests merged in 2019-07, with the labels that each got.

#119 use GA kubelet OS label
  assets/dns/daemonset.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#123 corefile: switch deprecated proxy plugin to forward plugin
  assets/dns/configmap.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns_configmap.go
Labels: approved, lgtm, size/M

#125 Bug 1726449: manifests: add version information
  manifests/0000_70_dns-operator_03-cluster-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
