Repository openshift/cluster-dns-operator, pull requests merged in 2019-10, with the labels that each got.

#132 syncOperatorStatus: Simplify relatedObjects
  pkg/operator/controller/status.go
Labels: approved, lgtm, size/XS

#133 DNS Operator hacking instructions for building the developed operator remotely on the cluster
  HACKING.md
  Makefile
  hack/buildconfig.yaml
  hack/create-buildconfig.sh
  hack/start-build.sh
Labels: approved, lgtm, size/L

#134 status: prevent degraded status flapping on rollout
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
Labels: approved, lgtm, size/M

#138 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
