Repository openshift/cluster-dns-operator, pull requests merged in 2019-05, with the labels that each got.

#103 Removes receiver from computeDNSStatusConditions func
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
Labels: approved, lgtm, size/XS

#102 Fixes operator deployment filename in release-local.sh
  hack/release-local.sh
Labels: approved, lgtm, size/XS

#92 Bug 1705032: Fix updating versions for dns cluster operator
  cmd/dns-operator/main.go
  manifests/0000_70_dns-operator_03-cluster-operator.yaml
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
Labels: approved, lgtm, size/L

#105 Fix hack/release.sh: Skip ClusterOperator resource creation
  hack/release-local.sh
  manifests/0000_70_dns-operator_03-cluster-operator.yaml
Labels: approved, lgtm, size/XS

#104 Bug 1690342: Update Progressing condition if upgrade happened
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
Labels: approved, lgtm, size/M

#106 Bug 1690342: Fix Progressing condition upgrade check
  pkg/operator/controller/status.go
Labels: approved, lgtm, size/S

#107 Bug 1706204: Fix tolerations
  manifests/0000_70_dns-operator_02-deployment.yaml
Labels: approved, lgtm, size/S

#108 Bug 1707062: Set terminationMessagePolicy=FallbackToLogsOnError for DNS operator and operands
  assets/dns/daemonset.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#110 Updates .gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#109 Bug 1711364: Report operator is degraded if any DNS is degraded
  pkg/operator/controller/status.go
  pkg/operator/controller/status_test.go
Labels: approved, lgtm, size/L

#111 Bug 1711439: Adds readiness probe to DaemonSet asset
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S
