Repository openshift/cluster-dns-operator, pull requests merged in 2020-08, with the labels that each got.

#182 Bug 1813062: ensures service IP is allocatable
  pkg/operator/controller/controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#186 [release-4.3] Bug 1859685: Tolerate all taints
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#189 Bug 1868816: Removes RestMapper in favor of pkg defaults
  pkg/operator/operator.go
  pkg/util/restmapper.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#187 Bug 1813062: Updates Status Reconciliation to Support DNS Service
  Makefile
  cmd/dns-operator/main.go
  hack/run-local.sh
  pkg/operator/config/config.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
  pkg/operator/controller/names.go
  pkg/operator/controller/status.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  pkg/operator/controller/status_test.go
  pkg/operator/operator.go
  test/e2e/operator_test.go
  test/e2e/utils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
