Repository openshift/cluster-dns-operator, pull requests merged in 2020-05, with the labels that each got.

#173 Bug 1838266: Updates Progressing status condition message
  pkg/operator/controller/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#166 Bug 1835725: computeOperatorDegradedCondition: Fix "NoDNS" check
  pkg/operator/controller/status.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#171 Bug 1813479: Tolerate all taints
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
