Repository openshift/cluster-dns-operator, pull requests merged in 2020-11, with the labels that each got.

#207 Bug 1895147: Remove memory limit on the CoreDNS container
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#212 addOwners-candita
  OWNERS
Labels: approved, lgtm

#210 Bug 1896923: Configure CoreDNS metrics plugin to use localhost
  cmd/dns-operator/main.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#213 Revert "Configure CoreDNS to shut down gracefully"
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, lgtm
