Repository openshift/cluster-dns-operator, pull requests merged in 2020-04, with the labels that each got.

#167 Add a dependency verification script
  Makefile
  hack/verify-deps.sh
Labels: approved, lgtm

#163 Bug 1809197: Secure CoreDNS metrics
  assets/dns/cluster-role.yaml
  assets/dns/daemonset.yaml
  assets/dns/service.yaml
  cmd/dns-operator/main.go
  manifests/0000_70_dns-operator_00-cluster-role.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/config/config.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_cluster_role.go
  pkg/operator/controller/controller_cluster_role_test.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/controller_dns_service_test.go
  pkg/operator/controller/controller_service_monitor.go
  pkg/operator/controller/controller_service_monitor_test.go
  pkg/operator/controller/names.go
  pkg/operator/operator.go
Labels: approved, bugzilla/valid-bug, lgtm

#170 Bug 1826885: DNS Service Monitor & Daemonset fixes
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/controller_service_monitor_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#168 Bug 1826996: Adds DNS Forwarding e2e Test
  test/e2e/operator_test.go
  test/e2e/utils.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
