Repository openshift/cluster-dns-operator, pull requests merged in 2020-03, with the labels that each got.

#157 Delete configmap asset
  assets/dns/configmap.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#156 Bug 1805177: Prefer node-local endpoints
  assets/dns/service.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#160 daemonset: Decrease default CPU request relative to SDN
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#158 Fix Bugzilla link and add GitHub issue template configuration
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: approved, lgtm

#159 Apply changes to service resource
  assets/dns/service.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/controller_dns_service_test.go
Labels: approved, lgtm
