Repository openshift/cluster-dns-operator, pull requests merged in 2020-07, with the labels that each got.

#174 Bug 1842741: Fix serviceChanged and daemonsetConfigChanged
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/controller_dns_service_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#180 Update go.mod for controller-tools & controller-runtime
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/internal/eventsource.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
Labels: approved, lgtm

#184 Port coredns errors alert
  manifests/0000_90_dns-operator_03_prometheusrules.yaml
Labels: approved, lgtm

#179 [release-4.4] Bug 1847197: Tolerate all taints
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
