Repository openshift/cluster-dns-operator, pull requests merged in 2021-03, with the labels that each got.

#236 [release-4.6] Bug 1928773: Set CoreDNS readiness probe period and timeout each to 3 seconds
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#240 Bug 1933761: Set CoreDNS's cache's maximum TTL to 900 seconds
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#241 Bug 1934905: Enable errors plugin for custom upstream resolvers
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#244 Give CoreDNS access to endpointslices
  assets/dns/cluster-role.yaml
  manifests/0000_70_dns-operator_00-cluster-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#237 Bug 1884053: Configure CoreDNS to shut down gracefully
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#239 NE-515: Alerts: Update prometheus alert rules for CoreDNS v1.8.z
  manifests/0000_90_dns-operator_03_prometheusrules.yaml
Labels: approved, lgtm

#242 Bug 1935297: Set CoreDNS readiness probe period and timeout each to 3 seconds
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#247 [release-4.7] Bug 1937089: Configure CoreDNS to shut down gracefully
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#243 Bug 1936022: Fix spurious reconciliation of DNS daemonset and service
  pkg/operator/controller/controller_cluster_role.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/controller_dns_service_test.go
  pkg/operator/controller/controller_service_monitor.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#253 Bug 1943578: Corefile: Use 30 second max TTL for caching of negative responses
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#209 Add node-resolver daemonset
  assets/dns/daemonset.yaml
  assets/node-resolver/service-account.yaml
  assets/node-resolver/update-node-resolver.sh
  go.mod
  go.sum
  manifests/0000_70_dns-operator_00-cluster-role.yaml
  manifests/0000_70_dns-operator_00-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset_test.go
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
  pkg/operator/controller/names.go
  test/e2e/operator_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm

#255 node-resolver: Use "kubernetes.io/os" node label
  pkg/operator/controller/controller_dns_node_resolver_daemonset.go
Labels: approved, lgtm
