Repository openshift/cluster-dns-operator, pull requests merged in 2021-04, with the labels that each got.

#248 [release-4.6] Bug 1937090: Configure CoreDNS to shut down gracefully
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#258 Bug 1946893: update inconsistent error message for AvailableCondition
  pkg/operator/controller/dns_status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#259 Add management workload annotations
  assets/dns/daemonset.yaml
  assets/dns/namespace.yaml
  manifests/0000_70_dns-operator_00-namespace.yaml
  manifests/0000_70_dns-operator_02-deployment-ibm-cloud-managed.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset.go
Labels: approved, bugzilla/valid-bug, lgtm

#266 Bug 1949361: Corefile: Enable bufsize plugin for all servers
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#262 Bug 1946929: Fix status reporting for default node placement
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
  pkg/operator/controller/status/controller.go
  pkg/operator/controller/status/controller_test.go
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#270 Bug 1953280: node-resolver: Set owner reference on the dns
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#265 Bug 1950270: go.mod: Update openshift/api & go version
  go.mod
  go.sum
  manifests/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#263 Bug 1948232: Fix for daemonset's maxSurge and service's ipFamilies and ipFamilyPolicy defaulting
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset_test.go
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/controller_dns_service_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#264 Rename workload annotations
  assets/dns/daemonset.yaml
  manifests/0000_70_dns-operator_02-deployment-ibm-cloud-managed.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_node_resolver_daemonset.go
Labels: approved, bugzilla/valid-bug, lgtm

#267 [release-4.7] Bug 1953097: Corefile: Enable bufsize plugin for all servers
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
