Repository openshift/cluster-dns-operator, pull requests merged in 2021-01, with the labels that each got.

#226 Bug 1908891: test/e2e: Block on TestCoreDNSImageUpgrade image revert
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#225 Bug 1905323: Request appropriate memory for dns-node-resolver container
  assets/dns/daemonset.yaml
  manifests/0000_70_dns-operator_02-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#230 Bug 1912522: test/e2e: Re-enable TestCoreDNSImageUprade
  test/e2e/operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#219 [release-4.6] Bug 1903887: Set DNS DaemonSet's maxUnavailable value to 10%
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#231 [release-4.6] Bug 1916907: Prevent dig errors from corrupting host's /etc/hosts
  assets/dns/daemonset.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
