Repository openshift/cluster-dns-operator, pull requests merged in 2022-01, with the labels that each got.

#309 Bug 2031699: Fix CoreDNS config ipv6 addresses should be always upper…
  go.mod
  go.sum
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#310 Bug 2031685: Fix duplicate /etc/resolv.conf in configmap
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#312 Added gcs278 to OWNERS
  OWNERS
Labels: approved, lgtm
