Repository openshift/cluster-dns-operator, pull requests merged in 2022-06, with the labels that each got.

#325 Bug 2093236: propagate retry request for progressing updates
  pkg/operator/controller/controller.go
  pkg/operator/controller/dns_status.go
  pkg/operator/controller/dns_status_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#322 Bug 2095941: topology aware hints to prefer to keep dns traffic within a zone
  pkg/operator/controller/controller_dns_service.go
  pkg/operator/controller/controller_dns_service_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#321 Bug 2092509: Append an error when a non-existent configmap is configured for DNS-over-TLS
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_cabundle_configmap.go
  pkg/operator/controller/controller_cabundle_configmap_test.go
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
  pkg/operator/controller/controller_dns_daemonset.go
  pkg/operator/controller/controller_dns_daemonset_test.go
  pkg/operator/controller/testdata/tls_with_non_existing_cabundle
  test/e2e/operator_test.go
  test/e2e/utils.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, bugzilla/severity-high
