Repository openshift/cluster-dns-operator, pull requests merged in 2023-07, with the labels that each got.

#372 [release-4.13] OCPBUGS-15225: Add support for protocolStrategy API field to enable force_tcp configuration
  go.mod
  go.sum
  manifests/0000_70_dns-operator_00.crd.yaml
  pkg/operator/controller/controller_dns_configmap.go
  pkg/operator/controller/controller_dns_configmap_test.go
  pkg/operator/controller/testdata/forwardplugin_protocolstrategy_none
  pkg/operator/controller/testdata/forwardplugin_protocolstrategy_tcp
  pkg/operator/controller/testdata/upstreamresolver_protocolstrategy_none
  pkg/operator/controller/testdata/upstreamresolver_protocolstrategy_tcp
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#374 OCPBUGS-12863: Replace Bugzilla link with Red Hat Issue Tracker
  .github/ISSUE_TEMPLATE/config.yml
  OWNERS
  README.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#361 NE-1268: Replace bindata using embed
  Makefile
  go.mod
  go.sum
  hack/update-generated-bindata.sh
  hack/verify-generated-bindata.sh
  pkg/manifests/assets/dns/cluster-role-binding.yaml
  pkg/manifests/assets/dns/cluster-role.yaml
  pkg/manifests/assets/dns/daemonset.yaml
  pkg/manifests/assets/dns/metrics/cluster-role-binding.yaml
  pkg/manifests/assets/dns/metrics/cluster-role.yaml
  pkg/manifests/assets/dns/metrics/role-binding.yaml
  pkg/manifests/assets/dns/metrics/role.yaml
  pkg/manifests/assets/dns/namespace.yaml
  pkg/manifests/assets/dns/service-account.yaml
  pkg/manifests/assets/dns/service.yaml
  pkg/manifests/assets/node-resolver/service-account.yaml
  pkg/manifests/assets/node-resolver/update-node-resolver.sh
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  tools/tools.go
  vendor/github.com/kevinburke/go-bindata/.gitignore
  vendor/github.com/kevinburke/go-bindata/.mailmap
  vendor/github.com/kevinburke/go-bindata/.travis.yml
  vendor/github.com/kevinburke/go-bindata/AUTHORS.txt
  vendor/github.com/kevinburke/go-bindata/CONTRIBUTING.md
  vendor/github.com/kevinburke/go-bindata/LICENSE
  vendor/github.com/kevinburke/go-bindata/Makefile
  vendor/github.com/kevinburke/go-bindata/README.md
  vendor/github.com/kevinburke/go-bindata/asset.go
  vendor/github.com/kevinburke/go-bindata/bits.go
  vendor/github.com/kevinburke/go-bindata/bytewriter.go
  vendor/github.com/kevinburke/go-bindata/config.go
  vendor/github.com/kevinburke/go-bindata/convert.go
  vendor/github.com/kevinburke/go-bindata/debug.go
  vendor/github.com/kevinburke/go-bindata/doc.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/main.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/version.go
  vendor/github.com/kevinburke/go-bindata/release.go
  vendor/github.com/kevinburke/go-bindata/restore.go
  vendor/github.com/kevinburke/go-bindata/safefile.go
  vendor/github.com/kevinburke/go-bindata/stringwriter.go
  vendor/github.com/kevinburke/go-bindata/toc.go
  vendor/modules.txt
Labels: approved, lgtm, docs-approved, qe-approved, px-approved, jira/valid-reference
